<?php

namespace Tests\Unit;

use App\Exceptions\CompressedFileTypeException;
use App\Services\CompressionService;
use Tests\TestCase;

class CompressionTest extends TestCase
{
    /**
     * @var CompressionService
     */
    protected CompressionService $compression;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->compression = $this->app->make(CompressionService::class);
    }

    public function testCompressedFileIsMadeCorrectlyWithDefinedType()
    {
        $compressedFiled = $this->compression->compress();

        $this->assertStringEndsWith(
            config("compression.fileType"),
            $compressedFiled
        );
    }

    public function testCompressedFileIsNotMadeWithIncorrectDefinedType()
    {
        $compressedFiled = $this->compression->compress();

        $this->assertStringNotContainsString(
            "mp4",
            $compressedFiled
        );
    }

    public function testCompressedFileIsNotMadeWithWrongType()
    {
        $this->expectException(CompressedFileTypeException::class);

        $this->compression->setType("mp4");
        $this->compression->compress();
    }
}
